namespace = "sbtree"

[functional]
path = "sbtree::BenchFn"
mem_size = 512
timeout = 10
concurrency = 100


[messaging]
path = "sbtree::BTreeActor"
mem_size = 4096
timeout = 10
fn_mem = 1024
caller_mem = 512