namespace = "sbtree"
dependencies = ["wal", "functional"]


[[handlers]]
name = "sbactor"
subsystem = "functional"
path = "sbtree::BTreeActor"
mem = 3538
timeout = 30
persistent = true
unique = true
scaleup = 0.0


[[handlers]]
name = "sbbench"
subsystem = "functional"
path = "sbtree::BenchFn"
mem = 512
scaleup = -1.0
timeout = 30
concurrency = 1