namespace = "sbtree"

[functional]
path = "sbtree::BenchFn"
mem_size = 128
timeout = 10
concurrency = 100

[messaging]
path = "sbtree::BTreeActor"
mem_size = 512
timeout = 10
fn_mem = 128
caller_mem = 127 # Hack to indicate 1GB for persistence scaling.